### PR TITLE
add distinct operator

### PR DESCRIPTION
**Pull request by gchudnov**
implemented using `std::unordered_set`.
`value` is used as a key.

### CODE REVIEW

**Comment by gchudnov** [comment]
closes #189

**Comment by gchudnov** [comment]
hm.. I see a problem in Clang.
Not sure how to fix it properly.

Looking at the error log, it seems when Clang tries to deduce the result type for dictinct() method, it ends up trying to instantiate something like:

```
'std::__1::hash<rxcpp::observable<int, rxcpp::dynamic_observable<int> > >'
```
for test/amb.cpp

or
```
'std::__1::hash<std::__1::vector<int, std::__1::allocator<int> > >'
```
for test/buffer.cpp

and fails.

Any ideas?

**Comment by kirkshoop** [comment]
So cool to see this PR!

I took a look at the error in clang and saw
```sh
... error: implicit instantiation of undefined template 'std::__1::hash<rxcpp::observable<int, rxcpp::dynamic_observable<int> > >'
```

There is no implementation of `std::hash<>` for `rxcpp::observable<>`. This means that the `distinct()` method on observable<> must use enable_if or some other mechanism to only be 'enabled' when `std::hash<>` is defined for the `value_type` of the `observable<>`

**Comment by gchudnov** [comment]
Right, but there is a problem with the following `static_assert` in [/libcxx/blob/master/include/functional](https://github.com/llvm-mirror/libcxx/blob/master/include/functional#L2557) for c++14 and above.

**Comment by gchudnov** [comment]
Here is an example that triggers the assertion for c++14 and libc++:
```c++
#include <iostream>
#include <unordered_set>
#include <functional>
#include <type_traits>

class A {};
class B {};

namespace std {
  template <> struct hash<B> {
    size_t operator()(const B& x) const {
      return 0;
    }
  };
}

template<typename, typename = void>
struct is_hashable
    : std::false_type {};

template<typename T>
struct is_hashable<T, typename std::enable_if<!!sizeof(std::declval<std::hash<T>>()(std::declval<T>()))>::type>
    : std::true_type {};

int main() {
  std::cout << is_hashable<A>::value << std::endl;
  return 0;
}
```

**Comment by kirkshoop** [comment]
I found one workaround, there may be others. I added this:
```cpp
namespace std {
  template <> struct hash<A>;
}
```
and the is_hashable test compiled and printed `0` when it ran.

Adding a declaration for `observable<>` at the end of rx-predef.hpp
```cpp
// disable std::hash for observable<>
namespace std {
  template <class T, class Source> struct hash<rxcpp::observable<T, Source>>;
  template <class T, class Source> struct hash<rxcpp::connectable_observable<T, Source>>;
  template <class K, class T, class Source> struct hash<rxcpp::grouped_observable<K, T, Source>>;
}
```

This appeared to work for me.

**Comment by gchudnov** [comment]
Thank you!
made some changes, please review.

**Comment by kirkshoop** [comment]
This rabbit hole just turned into a black hole. The workaround is not tenable since it requires every observable value type to have a std::hash declaration even if it will never use distinct(). 

This 3 year old question on [stackoverflow](http://stackoverflow.com/questions/12753997/check-if-type-is-hashable) indicates this is a longstanding issue that is still impeding usage. 

switching to a std::set might be a workaround. 
removing distinct() from observable would also work (the distinct() operator would still work).

```cpp
namespace Rx {
  using rxcpp;
  using rxcpp::sources;
  using rxcpp::operators;
}
Rx::range(0) | 
  Rx::distinct() | 
  Rx::take(5);
```

or adding a template arg to the distinct() member on observable so that it is not compiled until it is referenced (Sadly, this means that usage would get uglier `Rx.range(0).distinct<int>(); or Rx.range(0).distinct(0);`).

Thoughts?

Kirk

**Comment by kirkshoop** [comment]
I tried reversing the problem and built an rxcpp whitelist of hashable types that is extensible. I pushed the result to my fork: [branch](https://github.com/kirkshoop/RxCpp/tree/distinct), [change](https://github.com/kirkshoop/RxCpp/commit/dd1965d689b9f906efb04669421c1ecbca945f7d)

This is probably the best balance of tradeoffs of the options I have seen. What do you think?

**Comment by gchudnov** [comment]
You are right, that's a good trade-off.

Removing distinct() might be inconsistent with the rest of operators. And adding a template argument is ugly, I tried it yesterday. :)

**Comment by kirkshoop** [comment]
ok, i made a PR for this + the whitelist to trigger appveyor and travisci. If it passes I will merge.

Thanks for your contribution!

**Comment by kirkshoop** [comment]
thanks @gchudnov!

**Comment by gchudnov** [comment]
Thank you!

**Pull request merged**
