### PR TITLE
Prefer std::make_shared<T> to using std::shared_ptr(new T())

### PR DESCRIPTION
**Pull request by BenPope**

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@BenPope__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by kirkshoop** [comment]
I agree. I was having trouble with a compiler in the past when I used make_shared in these contexts. Since appveyor and travisci are happy I would like to take this.
Please sign the CLA (just once will do).

**Comment by msotclas** [comment]
__@BenPope__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by kirkshoop** [comment]
Thanks! - rebased and merged b38a4f085b9abd9dba694964e5bc68e1a92f3fb8

**Pull request closed without merging**
