### PR TITLE
Change the way statics work to avoid RXCPP_SELECT_ANY

### PR DESCRIPTION
**Pull request by BenPope**
clang-3.6 wouldn't link, it had lots of errors like:
```
`.text.startup' referenced in section `.text.startup' of CMakeFiles/rxcppv2_test.dir/RxCpp/Rx/v2/test/subscriptions/subscription.cpp.o: defined in discarded section `.text.startup[_ZN5rxcpp22composite_subscription12shared_emptyE]' of CMakeFiles/rxcppv2_test.dir/RxCpp/Rx/v2/test/subscriptions/subscription.cpp.o 
```

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@BenPope__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by kirkshoop** [comment]
This is great! Please sign the CLA (just once will do) I would love to take this.

**Comment by BenPope** [comment]
I hope to have the CLA countersigned soon.

**Comment by kirkshoop** [comment]
I have been looking for the CLA to arrive. Did you use [CLA2](https://cla2.msopentech.com/) ?

**Comment by BenPope** [comment]
I'm hoping it will be countersigned soon, I haven't forgotten about it.

**Comment by jpattersonz** [comment]
Is the goal still to get this pull request committed?

reference:
https://github.com/Reactive-Extensions/RxCpp/issues/39

It appears that the introduction of RXCPP_SELECT_ANY was to solve this issue (which was my issue!).  Interestingly enough, I just switched off of V 2.1.1 from nuget and on to the GitHub master branch, and these RXCPP_SELECT_ANY statics are causing Visual Studio 2013 Update 4 to hang!  Specifically this one:
RXCPP_SELECT_ANY const scheduler event_loop::instance = make_scheduler<event_loop>();


I'm fairly certain Ben's changes would fix this for me.

**Comment by kirkshoop** [comment]
Hi, I wanted to let you know that the CLA process has changed and your employer does not need to sign. Please sign the CLA again [here](https://cla2.msopentech.com/).

**Comment by msotclas** [comment]
__@BenPope__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by kirkshoop** [comment]
Thanks! - rebased and merged 71254f2e6a51fe861869f22a1eaebd9d09001132
Please check my merge - there were conflicts in rx-notifications and rx-test.

**Pull request closed without merging**
