### PR TITLE
add vs2017 RC to appveyor

### PR DESCRIPTION
**Pull request by kirkshoop**

### CODE REVIEW

**Comment by gchudnov** [comment]
@kirkshoop,
It looks Visual Studio 2017 was added to your account on Appveyor...
Guess the PR can be merged now, what do you think?

**Comment by gchudnov** [comment]
Beg pardon, it looks a lot of activity happening here the last week and I got sick.. :(

**Comment by kirkshoop** [comment]
yes, I think we can merge it now.

sorry, that you were sick, I hope you are feeling better!

**Comment by gchudnov** [comment]
Merged, thank you!

**Pull request merged**
