### PR TITLE
Implement pairwise operator

### PR DESCRIPTION
**Pull request by cirla**

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@cirla__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by cirla** [comment]
I completed the signed CLA at 16:21 EST today.

**Comment by kirkshoop** [comment]
Thanks!

just waiting for the cla process to finish. The travisci failure is an environment issue, don't worry about it.

**Comment by cirla** [comment]
I submitted through https://cla.msopentech.com/ earlier, just submitted again through https://cla2.msopentech.com/.

**Comment by kirkshoop** [comment]
thanks! - cla2 will finish faster.

**Comment by msotclas** [comment]
__@cirla__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Pull request merged**
