### PR TITLE
add min and max operators

### PR DESCRIPTION
**Pull request by gchudnov**
Added min and max operators.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@gchudnov__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by kirkshoop** [comment]
Thanks! this looks great!

I would merge this now, but I need to make some changes to placate travisci - it is soo difficult to keep a C++ build stable on travisci.

**Comment by kirkshoop** [comment]
I debased and merged in #182

**Comment by kirkshoop** [comment]
Um. Rebased not debased.

**Comment by gchudnov** [comment]
Thank you!

**Pull request closed without merging**
