### PR TITLE
Added time_interval operator

### PR DESCRIPTION
**Pull request by gchudnov**
Added [time_interval](http://reactivex.io/documentation/operators/timeinterval.html) operator, please review.

Thank you,
Grigoriy

### CODE REVIEW

**Comment by gchudnov** [comment]
Guess, the problem with clang-build should be ignored. It was caused by the disabled apt-repository.

**Comment by kirkshoop** [comment]
yes, I am waiting for hana or rangev3 to find a solution for clang.

**Comment by kirkshoop** [comment]
rebased and pushed, Thanks!

**Comment by gchudnov** [comment]
I can't see it in the [history](https://github.com/Reactive-Extensions/RxCpp/commits/master), have you pushed it?

**Comment by kirkshoop** [comment]
balderdash

I pushed instead of creating a new PR and did not see the push result "everything is up to date".
Now it is pushed.

```shell
$ git push mirror master
Counting objects: 22, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (20/20), done.
Writing objects: 100% (22/22), 5.55 KiB | 0 bytes/s, done.
Total 22 (delta 12), reused 0 (delta 0)
To https://github.com/Reactive-Extensions/RxCpp.git
   ac91791..1b1e5ed  master -> master
```

**Comment by gchudnov** [comment]
Thank you!

**Pull request closed without merging**
