### PR TITLE
decouple start_with from observable

### PR DESCRIPTION
**Pull request by gchudnov**
Decoupled `start_with` from observable, added tests.
Please review...

Thank you,
Grigoriy

### CODE REVIEW

**Comment by gchudnov** [comment]
It seems I bumped into the same problem with VC2013 again:
`fatal error C1045: compiler limit : linkage specifications nested too deeply`
Will need some time to figure it out...

**Comment by gchudnov** [comment]
slightly changed the implementation, hope it fixes msvc2013.
The error `fatal error C1045: compiler limit : linkage specifications nested too deeply` is quite painful.. :disappointed:

**Comment by kirkshoop** [comment]
Yes, I know. When I rewrite rxcpp I will use at least c++14 and vs2013 will not be supported!

**Comment by kirkshoop** [comment]
Thank you!

Perhaps I should poll on twitter for vs2013 usage?

**Comment by gchudnov** [comment]
> Perhaps I should poll on twitter for vs2013 usage?

Guess, there is no need if the next major version won't use it anyway...
There might be some issues with vs2013 in v2, but I don't think they will be the show-stoppers..

I've seen the v3 in your repo. What stops making it the next major version? Or is that thing is a pure experiment?

**Comment by kirkshoop** [comment]
Some parts of v3 need another pass (context and scheduler) the rest I am pretty happy with. 

I think that the observable decoupling will be the last big transform in the v2 code. Hopefully v3 can be polished up and put into the official repo as the eventual replacement during this year.

**Pull request merged**
