### PR TITLE
decouple switch_if_empty, default_if_empty from observable

### PR DESCRIPTION
**Pull request by gchudnov**
Decoupled `switch_if_empty`, `default_if_empty` from observable,
please review.

Thank you,
Grigoriy

### CODE REVIEW

**Comment by gchudnov** [comment]
@kirkshoop,
MSVC2013 fails with `fatal error C1045: compiler limit : linkage specifications nested too deeply`
Have you bumped into it?

Don't have MSVC2013 at hand, not sure what is the best way to fix it... :slightly_frowning_face: 
Probably by replacing `from` to `iterate`?

**Comment by kirkshoop** [comment]
@gchudnov - yes this is a bad fixed compiler limit. There are only a fixed number of nested decltype() allowed. I was eventually able to fix this recently by finding a way to remove a level of decltype(). I had to find the offending decltype by laboriously reducing the code until I found which one was too deeply nested.

**Comment by gchudnov** [comment]
should work now... :smile:

**Comment by kirkshoop** [comment]
Nice! Thank you!

**Pull request merged**
