### PR TITLE
updated Catch to latest

### PR DESCRIPTION
**Pull request by aargor**
This is the pull request to fix issue #352 .

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@aargor__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by kirkshoop** [comment]
Thanks!

vs2013 warns that the assignment operator cannot be generated

```shell
c:\projects\rxcpp-446\ext\catch\include\internal\catch_expression_lhs.hpp(100): warning C4512: 'Catch::ExpressionLhs<const std::vector<rxcpp::notifications::recorded<std::shared_ptr<_Ty>>,std::allocator<rxcpp::notifications::recorded<std::shared_ptr<_Ty>>>> &>' : assignment operator could not be generated [C:\projects\rxcpp-446\build\test\rxcpp_test_all.vcxproj]
          with
          [
              _Ty=rxcpp::notifications::detail::notification_base<bool>
          ]
          C:\projects\rxcpp-446\Rx\v2\test\operators\all.cpp(34)
```

**Comment by aargor** [comment]
Yup! It looks like there's a compatibility issue between the latest version of Catch and VS2013. It may be that the best way to resolve this is to cherry pick the correctness patches from Catch. I am referring to these: https://github.com/philsquared/Catch/pull/728. I think those are the only things needed to ensure RxCPP builds with the more rigorous VS2017.

**Comment by gchudnov** [comment]
hm.. right, it looks there is an issue in Catch. Just made a PR( philsquared/Catch#824 ) to fix it. If accepted, it should allow dependency on the latest Catch version.

**Comment by aargor** [comment]
It hadn't occurred to me to try to patch this new issue in Catch as well. Neat! :). I suppose I'll hold off until that develops, thanks.

**Comment by kirkshoop** [comment]
@aargor, please update to the latest catch and try again. the PR was merged.

Thanks!

**Comment by aargor** [comment]
Thanks for the ping! Just pushed (to my fork).

**Comment by kirkshoop** [comment]
Thank You!

**Pull request merged**
