### PR TITLE
Don't return std::move(t); It prevents NRVO and is almost always wrong

### PR DESCRIPTION
**Pull request by BenPope**

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@BenPope__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by kirkshoop** [comment]
agreed! thanks! Please sign the CLA (just once will do) I would love to take this.

**Comment by msotclas** [comment]
__@BenPope__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by kirkshoop** [comment]
Thanks! - rebased and merged d7a795119a52d76fba64a8bf2fa672575e07a012

**Pull request closed without merging**
