### PR TITLE
 * fixed select_many -> it deleted a collection and accessed it afte…

### PR DESCRIPTION
**Pull request by alexeymarkov**
…rwards which leaded to crashes

* added to_list and to_set
* fixed ::from(Collection& c) compile errors -> it required "using namespace std;" to be able to find begin(c) and end (c)

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@alexeymarkov__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by kirkshoop** [comment]
Thanks! looks good! 

don't worry about the travis failure, it is due to changes in the travis service, not changes in the rxcpp code.

once the CLA is cleared I will be happy to merge.

**Comment by kirkshoop** [comment]
Thanks for the changes.  
Will you sign the cla?

**Comment by alexeymarkov** [comment]
Hi,

I will do that right now.
Also I did another crash fix for select_many and will create a new pull
request.

Alexey

2015-12-17 15:20 GMT+01:00 Kirk Shoop <notifications@github.com>:

**Comment by msotclas** [comment]
__@alexeymarkov__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by kirkshoop** [comment]
Thanks! rebased and pushed.

**Pull request closed without merging**
