### PR TITLE
move sources docs out of observable

### PR DESCRIPTION
**Pull request by kirkshoop**
shift tests to include aliases

### CODE REVIEW

**Comment by gchudnov** [comment]
Looks great!
Thank you!

**Comment by gchudnov** [comment]
@kirkshoop,

Could you provide some details on the roadmap?
Basically what is the plan for V2 and V3?

Thank you!

**Comment by kirkshoop** [comment]
@gchudnov Thanks!

I do not have a roadmap, please suggest things that you would like to see done. 

I was planning to let v2 bake for a week and then do a release with all the observable decoupling work you have done.

My thoughts on [starting v3](https://github.com/Reactive-Extensions/RxCpp/issues/347).

**Comment by gchudnov** [comment]
got it, thank you!
Didn't have time to look at V3 prototype, need some time..

**Pull request merged**
