### PR TITLE
decouple skip_until from observable

### PR DESCRIPTION
**Pull request by gchudnov**
Decoupled `skip_until` from observable.
To make it similar to `take_until`, added a version of skip_until with a time point.
Please review.

Thank you,
Grigoriy

### CODE REVIEW

**Comment by gchudnov** [comment]
@kirkshoop 
btw, do you mind if a make std::chrono::milliseconds in the [test scheduler](https://github.com/Reactive-Extensions/RxCpp/blob/master/Rx/v2/src/rxcpp/schedulers/rx-test.hpp#L48-L53) a typedef, something like:

```
typedef std::chrono::milliseconds duration_type;
```

In this way tests can be written in terms of that `duration_type`, instead of specifying milliseconds [explicitly](https://github.com/Reactive-Extensions/RxCpp/pull/320/files#diff-b7592a63bb4a4c2dfc8252e0e5e6f2c8R580):

Instead of:
```
 clock_type::time_point t(std::chrono::milliseconds(225));
```

there will be:
```
 clock_type::time_point t(duration_type(225));
```

**Comment by kirkshoop** [comment]
@gchudnov, yes, I think removing the explicit milliseconds from the tests is a good idea. 

Perhaps, instead of a typedef, we could expose to_time_point() on the test scheduler by calling the same method on the shared state. 

Thus auto t = sc.to_time_point(225); would replace the manual construction of the time_point from the duration.

**Comment by kirkshoop** [comment]
Thank you for making the _until methods consistent as well!

**Comment by gchudnov** [comment]
done #321, please take a look

**Pull request merged**
